version: 2
jobs:
  pdax_web_staging
    docker:
      - image: node:8.11.3
    steps:
      - checkout
      - run: echo "A first hello"
  #pdax_web_prod:
  #  docker:
  #    - image: node:8.11.3
  #  working_directory: /go/src/github.com/PixoPH/backend/deployment-tools
  #   steps:
  #     - checkout:
  #         path: /go/src/github.com/PixoPH/pixo-web
  #     - run: |
  #         echo "test"

workflows:
  version: 2
  pdax-web-deployement:
    jobs:
      - pdax_web_staging:
          filters:
            branches:
              only:
                - staging
#      - pdax_web_prod:
#          filters:
#            branches:
#              only:
#                - master
