version: 2
jobs:
  build:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: node:alpine
    steps:
      - checkout
      - run: |
          npm install -g create-react-app@1.5.2
          create-react-app sample-app
          cd sample-app
          npm start
      
