version: 2
jobs:
  deploy_pdax_web_staging:
    docker:
      - image: node:8.11.3
    steps:
      - checkout
      - run: echo "A first hello. Test!"

workflows:
  version: 2
  deploy-pdax-web:
    jobs:
      - deploy_pdax_web_staging:
          filters:
            branches:
              only:
                - staging
