version: 2
jobs:
  deploy_pdax_web_staging:
    docker:
      - image: node:8.11.3
    steps:
      - checkout
      - run: echo "A first hello"

workflows:
  version: 2
  deploy_and_test:
    jobs:
      - deploy_pdax_web_staging
