version: 2
jobs:
  one:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: ubuntu:16.04  #circleci/ruby:2.4.1-jessie
    steps:
      - checkout
      - run: |
          echo "test"
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
