version: 2
jobs:
  deploy_pdax_web_prod:
    docker:
      - image: node:8.11.3
      #- image: ubuntu:16.04
    #working_directory: /home/ubuntu
    steps:
      - checkout
          #path: /go/src/github.com/PixoPH/pixo-web
      - run: echo "Test!"
      - run: useradd ubuntu
      #- run:
          #name: push build to s3
          #  command: aws deploy push --application-name pdax-web --s3-location s3://pdax-circleci/pdax-web-prod --ignore-hidden-files --region=ap-southeast-1 

workflows:
  version: 2
  deploy-pdax-web:
    jobs:
      - deploy_pdax_web_prod:
          filters:
            branches:
              only:
                - master
