version: 2
jobs:
  deploy_pdax_web_staging:
    docker:
      - image: ubuntu:16.04
    working_directory: /home/ubuntu/pdax-web
    steps:
      - checkout:
          path: /home/ubuntu/pdax-web/scripts/deploy
      - run: apt-get update -y >/dev/null 2>&1 && apt-get install python-pip sudo python-dev gzip zip -y >/dev/null 2>&1
      - run: sudo pip install awscli >/dev/null 2>&1 #install aws cli
      - run: aws s3 cp s3://pdax-circleci/pdax-web-staging pdax-web-stagig.zip >/dev/null 2>&1 #copy from S3
      - run: unzip -qq -o pdax-web-stagig.zip -d /home/ubuntu/pdax-web #extract
      - run: rm -rf /home/ubuntu/pdax-web/pdax-web-staging.zip
      #- run: apt-get install -y curl
      #- run: apt-get install -y wget
      #- run: apt-get install -y ruby
      #- run: wget https://aws-codedeploy-ap-southeast-1.s3.amazonaws.com/latest/install -O /home/ubuntu/install
      #- run: chmod +x /home/ubuntu/install
      #- run: /home/ubuntu/install auto
      #- run: /home/ubuntu/pdax-web/scripts/deploy/install_dependencies.sh
      #- run: /home/ubuntu/pdax-web/scripts/deploy/after_install.sh 
      - run: |
          touch /home/ubuntu/pdax-web/scripts/deploy/deploy.sh   
          #echo "Creating codedeploy..."
          aws deploy push --application-name pdax-web-prod --s3-location s3://pdax-circleci/pdax-web-staging --ignore-hidden-files --region=ap-southeast-1 >> /home/ubuntu/pdax-web/scripts/deploy/deploy.sh
          sed -i "s#<deployment-group-name>#pdax-web-staging#g" /home/ubuntu/pdax-web/scripts/deploy/deploy.sh
          sed -i 's/--deployment-config-name <deployment-config-name>/--region=ap-southeast-1 --output text/' /home/ubuntu/pdax-web/scripts/deploy/deploy.sh
          sed -i 's#<description>#"PDAX Web Staging"#g' /home/ubuntu/pdax-web/scripts/deploy/deploy.sh
          sed -i '2,3d' /home/ubuntu/pdax-web/scripts/deploy/deploy.sh
          sed -i '2d' /home/ubuntu/pdax-web/scripts/deploy/deploy.sh
          cat /home/ubuntu/pdax-web/scripts/deploy/deploy.sh
          /bin/sh /home/ubuntu/pdax-web/scripts/deploy/deploy.sh
          
  deploy_pdax_web_prod:
    docker:
      - image: ubuntu:16.04
    working_directory: /home/ubuntu/pdax-web
    steps:
      - checkout:
          path: /home/ubuntu/pdax-web/scripts/deploy
      - run: apt-get update -y >/dev/null 2>&1 && apt-get install python-pip sudo python-dev gzip zip -y >/dev/null 2>&1
      - run: sudo pip install awscli >/dev/null 2>&1 #install aws cli
      - run: aws s3 cp s3://pdax-circleci/pdax-web-prod pdax-web-prod.zip >/dev/null 2>&1 #copy from S3
      - run: unzip -qq -o pdax-web-prod.zip -d /home/ubuntu/pdax-web #extract
      - run: rm -rf /home/ubuntu/pdax-web/pdax-web-staging.zip
      #- run: apt-get install -y curl
      #- run: apt-get install -y wget
      #- run: apt-get install -y ruby
      #- run: wget https://aws-codedeploy-ap-southeast-1.s3.amazonaws.com/latest/install -O /home/ubuntu/install
      #- run: chmod +x /home/ubuntu/install
      #- run: /home/ubuntu/install auto
      #- run: /home/ubuntu/pdax-web/scripts/deploy/install_dependencies.sh
      #- run: /home/ubuntu/pdax-web/scripts/deploy/after_install.sh 
      - run: |
          touch /home/ubuntu/pdax-web/scripts/deploy/deploy.sh   
          #echo "Creating codedeploy..."
          aws deploy push --application-name pdax-web-prod --s3-location s3://pdax-circleci/pdax-web-prod --ignore-hidden-files --region=ap-southeast-1 >> /home/ubuntu/pdax-web/scripts/deploy/deploy.sh
          sed -i "s#<deployment-group-name>#pdax-web-prod-v2#g" /home/ubuntu/pdax-web/scripts/deploy/deploy.sh
          sed -i 's/--deployment-config-name <deployment-config-name>/--region=ap-southeast-1 --output text/' /home/ubuntu/pdax-web/scripts/deploy/deploy.sh
          sed -i 's#<description>#"PDAX Web Production"#g' /home/ubuntu/pdax-web/scripts/deploy/deploy.sh
          #sed -i '2,3d' /home/ubuntu/pdax-web/scripts/deploy/deploy.sh
          #sed -i '2d' /home/ubuntu/pdax-web/scripts/deploy/deploy.sh
          cat /home/ubuntu/pdax-web/scripts/deploy/deploy.sh
          #/bin/sh /home/ubuntu/pdax-web/scripts/deploy/deploy.sh
  
workflows:
  version: 2
  deploy-pdax-web:
    jobs:
      - deploy_pdax_web_staging:
          filters:
            branches:
              only:
                - staging
      - deploy_pdax_web_prod:
          filters:
            branches:
              only:
                - master
