version: 2
jobs:
  deploy_pdax_web_staging:
    docker:
      - image: node:8.11.3
      #- image: ubuntu:16.04
    working_directory: /home/ubuntu/pdax-web #/opt/pdax-web
    steps:
      - checkout
          #path: /go/src/github.com/PixoPH/pixo-web
      #- run: echo "Test!"
      - run: apt-get update -y && apt-get install python-pip sudo python-dev gzip zip -y >/dev/null 2>&1
      - run: sudo pip install awscli >/dev/null 2>&1
      #- run: pip --version
      #- run: which aws
       #- run:
          #name: push build to s3
          #  command: aws deploy push --application-name pdax-web-staging --s3-location s3://pdax-circleci/pdax-web-staging --ignore-hidden-files --region=ap-southeast-1 
      - run: aws s3 cp s3://pdax-circleci/pdax-web-staging pdax-web-stagig.zip
      - run: rm README.md
      - run: unzip -p pdax-web-staging.zip #extract
      - run: ls -l /home/ubuntu/pdax-web  #/opt/pdax-web/
       
workflows:
  version: 2
  deploy-pdax-web:
    jobs:
      - deploy_pdax_web_staging:
          filters:
            branches:
              only:
                - master
